sudo: required
services:
    - docker

before_install:
    - docker build -t rkyuvraj/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true rkyuvraj/react-test npm test

after_success:
    - docker build -t rkyuvraj/fib-calc-app-client ./client
    - docker build -t rkyuvraj/fib-calc-app-nginx ./nginx
    - docker build -t rkyuvraj/fib-calc-app-api ./server
    - docker build -t rkyuvraj/fib-calc-app-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push rkyuvraj/fib-calc-app-client
    - docker push rkyuvraj/fib-calc-app-nginx
    - docker push rkyuvraj/fib-calc-app-api
    - docker push rkyuvraj/fib-calc-app-worker

deploy:
    provider: elasticbeanstalk
    region: ap-south-1
    app:  docker-fib-calculator
    env: DockerFibCalculator-env
    edge: true
    bucket_name: elasticbeanstalk-ap-south-1-214924494988
    bucket_path: docker-fib-calculator
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY